apiVersion: skaffold/v2beta4
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - context: .
      image: fastify-service-template
deploy:
  kubectl:
    manifests:
      - k8s/api-service-depl.yaml
