apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-depl
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
      tier: web
  template:
    metadata:
      labels:
        app: api-service
        tier: web
    spec:
      containers:
        - name: api-service
          image: gcr.io/teak-frame-342523/fastify-service-template:latest
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: gcr-json-key
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: api-service
# spec:
#   type: NodePort
#   selector:
#     app: api-service
#   ports:
#     - name: api-service
#       protocol: TCP
#       port: 8080
#       targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
    tier: web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: api-service
    tier: web
