apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-depl
  labels:
    app: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
      tier: web
  template:
    metadata:
      labels:
        app: api-service
        tier: web
    spec:
      containers:
        - name: api-service
          image: fastify-service-template:latest
          imagePullPolicy: Never
          ports:
          - containerPort: 8080

      #     image: gcr.io/teak-frame-342523/fastify-service-template:latest
      #     ports:
      #       - containerPort: 8080
      # imagePullSecrets:
      #   - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
    tier: web
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: api-service
    tier: web
